# Project information
site_name: NightWalker V0.1.0 Docs
site_description: NightWalker V0.1.0 User Documention
site_author: "chineseluo"
# site_favicon need a picture path
site_favicon: ""

# Repository
repo_name: NightWalker
repo_url: https://github.com/chineseluo/nightwalker

# Copyright
copyright: 'Copyright &copy; 2020 - 2020 chineseluo'

# Google Analytics
google_analytics: ['UA-36723568-3', 'auto']